config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
  resources :posts
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
     has_one_attached :image #each post has an attached image
     belongs_to :user # each post belongs to a user
     validates :user_id, presence: true
     # make sure uploaded file is an image, and is not larger than 500kb
     validates :image, file_size: { less_than_or_equal_to: 500.kilobytes }, file_content_type: { allow: ['image/jpeg', 'image/png'] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts, dependent: :destroy # a user can have many posts. if a user is deleted, so are their posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :username, presence: true, length: { minimum: 4,
  maximum: 16 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :owned_post, only: [:edit, :update, :destroy]


  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("created_at DESC")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
     @post = Post.find(params[:id])
     respond_to do |format|
          format.html { @post }
          # format.json { render json: @post, include: [:image, image: {include: {attachments: {include: {blob: {methods: :service_url} } } } }] }
          format.json { render json: @post, include: [:image] }
     end
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:caption, :image)
    end

    # only allow the correct user to view pages
    def owned_post
     unless current_user == @post.user
       flash[:alert] = "That post doesn't belong to you!"
       redirect_to root_path
   end end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

     private

     def sign_up_params
          params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
     end

     def account_update_params
          params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
     end
     
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navigation.html.erb
<nav class="dt w-100 border-box pa3 ph5-ns bg-white">
     <%= link_to root_path, class:"dtc v-mid mid-gray link dim w-50 pl7 tl f3" do %>
     <%= icon('fas', 'camera-retro', class:" grad1",) %>
     |<span class=" grad1"> Fins</span><span class="grad2">tagram</span>
  <% end %>
  <div class="dtc v-mid w-75 tr pr7">
     <% if user_signed_in? %>
          <%= link_to 'New Post',  new_post_path,class:"link dim blue f6 f5-ns dib mr3 mr4-ns" %>
          <%= link_to 'Logout', destroy_user_session_path, class:"link dim blue f6 f5-ns dib mr3 mr4-ns", method: :delete %>
     <% else %>   
          <%= link_to 'Log In', new_user_session_path,  class:"link dim blue f6 f5-ns dib mr3 mr4-ns" %>
          <%= link_to 'Join Us',  new_user_registration_path,class:"link dim blue f6 f5-ns dib mr3 mr4-ns" %>
     <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finstagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="sans-serif bg-light-gray">
  <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_feed.html.erb
<% @posts.each do | post | %>
     <%= link_to post, class:"no-underline" do %>
     <section class="tc pa3   pt3">
          <article class="hide-child relative ba b--black-20 mw6 center bg-white pt2 br3" style="max-width: 500px">
          <h1 class="tl f5 pl4 pb1 blue"><%= post.user.username %> </h1>

               <div class="mw-100">
                    <%= image_tag(post.image, class:"db") %>
               </div>
               <div class="pa2 bt b--black-20">
                    <p class="f6 gray mv1 tl pl2 pr2"><%= post.caption %></p>
                    <a class="link tc ph3 w-25 center pv1 db bg-animate bg-dark-blue hover-bg-blue white f6 br1" href="#">Comment</a>
               </div>               
               <% if current_user.id == post.user.id %>
                    <%= link_to edit_post_path(post), class:"  absolute top-1 right-1 f5 bw1 black-40  no-underline  pa2 lh-solid b" do%>
                              <%= icon('fas', 'edit', class:"",) %>
                    <% end %>
               <% end %>
          </article>
     </section>

     <% end %>
<% end %>

app/views/posts/_form.html.erb
<section class="tc pa3   pt4">
  <article class="hide-child relative ba b--black-20 mw6 center bg-white pt2 br3" style="max-width: 500px">
     
          <%= simple_form_for @post do |f| %>

          

          <div class="field">
               <div class='control'>
                    <%= f.file_field :image %>
               </div>
          </div>


          <div class="field">
               <div class='control'>
                    <%= f.input :caption, input_html: {class: 'input br3 bg-white'}, wrapper: false, label_html: {class: 'label'} %>
               </div>
          </div>


          <%= f.button :submit, 'share', class: 'button-is-primary white b--light-gray br3 bg-green' %>
          <% end %>
       </article>
</section>

app/views/posts/_image.html.erb
<section class="tc pa3  pt3">
  <article class="hide-child relative ba b--black-20 mw6 center bg-white pt2 br3 w-75" style="max-width: 500px">
  <h1 class="tl f5 pl4 pb1 blue"><%= @post.user.username%> </h1>

     <div class="mw-100">
          <%= image_tag(@post.image, class:"db") %>
     </div>
    <div class="pa2 bt b--black-20">
      <p class="f6 gray mv1 tl pl2 pr2"><%= @post.caption %></p>
      <a class="link tc ph3 w-25 center pv1 db bg-animate bg-dark-blue hover-bg-blue white f6 br1" href="#">Comment</a>
    </div>
    <% if current_user.id == @post.user.id %>
      
    
          <%= link_to edit_post_path(@post), class:"  absolute top-1 right-1 f5 bw1 black-40  no-underline  pa2 lh-solid b" do%>
          <%= icon('fas', 'edit', class:"",) %>
          <% end %>
    <% end %>
  </article>
</section>
<% if current_user.id == @post.user.id %>
<%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<%= render 'feed' %>


<br>

<%= link_to 'New Post', new_post_path %>

<style>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'image' %>

<% if current_user.id == @post.user.id %>
  <%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', posts_path %>